package myproject;

import java.util.Scanner;

class MyClass {   
    static Scanner userinput = new Scanner(System.in); 

    public static void main(String[] args){
        int i;
        for(i=1; i<5000; i=2*i+1){
             System.out.println("Count is: " + i);
        }
    }}
    
    
    
    
   //Code Functionality and Output Description

   //The provided Java code is a simple program that utilizes a for loop to generate and print a series of integers. The loop initializes an integer variable i starting at 1 and continues to iterate as long as i is less than 5000. Within each iteration, the current value of i is printed to the console with the message “Count is: “. After printing, the value of i is updated according to the expression 2*i + 1.

   // To break down the Process:

   //Initialization: The variable i starts at 1.
   //Loop Condition: The loop will continue as long as i < 5000.
   //Output Statement: Each iteration prints the current value of i.
   // Update Expression: After printing, i is updated using the formula 2*i + 1, which means in each subsequent iteration, i will grow exponentially.
   //The output of this code will be a series of numbers that are generated by repeatedly applying the formula until i reaches or exceeds 5000. Specifically, it will print:

   //Count is: 1
   // Count is: 3
   //Count is: 7
   // Count is: 15
   // Count is: 31
   // Count is: 63
   // Count is: 127
   //Count is: 255
   // Count is: 511
   // Count is: 1023
   //Count is: 2047
   // Count is: 4095
   // After reaching a point where applying the update expression results in a number greater than or equal to 5000 (which occurs when i becomes 8191), the loop terminates.
   // Sorry it got kinda weird formating as I copied it from my Word Doc to here
    
    